"""empty message

Revision ID: a1bdfd9921a8
Revises: 663e2536e713
Create Date: 2024-10-19 00:14:27.010143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1bdfd9921a8'
down_revision = '663e2536e713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('reservation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='reservationstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='reservationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('reservation_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
